---
driver:
  name: vagrant
  vm_hostname: chefsrv
  customize:
    memory: <%= ENV['CHEF_RAM'] %>
    cpus: <%= ENV['CHEF_CPU'] %>
    name: chefsrv
  network:
   - ['private_network', ip: '10.1.1.10']

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>

verifier:
  name: inspec

platforms:
  - name: mycsc-7.6

suites:
  - name: chefsrv
    run_list:
      - recipe[chefsrv::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
